### ISSUE TITLE
Possibility of applying this to Boorus

### ISSUE THREAD

**Issue by DonaldTsang** [takuti/wims-2015#7]
Context: Boorus are used to allow people to collectively tag images. However user tag approval is anonymized to only show the accuracy.
Is it possible for this system to create a Folksonomy if there is an alias/implication (hypernym/synonym) tree? https://derpibooru.org

**Comment by takuti** [comment]
@DonaldTsang Sorry for the late reply. Yes - It is certainly possible to apply the proposed technique to an image-tag dataset. Simply replace "web page" with "image". Actual implementation depends on how your data is represented though.

**Comment by BradKML** [comment]
@takuti regarding the documentation, the data is presented as an image with a list of tags in an unordered fashion (so CBOW and Skip-Gram will not necessarily work). Also, there will be a separate table for explicit hypernym and synonym two-column table, the former being a tree-like or hierarchical structure, the latter being more one-to-many.
